# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1900, 1000)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 2311, 1031))
        self.widget.setStyleSheet("background:rgb(0, 0, 0)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(550, 200, 931, 181))
        self.label.setStyleSheet("background:rgb(0, 0, 0);  color:rgb(255, 255, 127);\n"
"font: 25pt \"Pristina\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(700, 80, 651, 111))
        self.label_2.setStyleSheet("color:rgb(255, 0, 255);\n"
"font: 87 50pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(380, 470, 55, 16))
        self.label_3.setObjectName("label_3")
        self.Username = QtWidgets.QLineEdit(self.widget)
        self.Username.setGeometry(QtCore.QRect(760, 490, 481, 41))
        self.Username.setStyleSheet("background:rgb(255, 255, 255);\n"
"font: 10pt \"Candara\";")
        self.Username.setObjectName("Username")
        self.Enter = QtWidgets.QPushButton(self.widget)
        self.Enter.setGeometry(QtCore.QRect(950, 700, 111, 41))
        self.Enter.setStyleSheet("Background:rgb(0, 255, 0);\n"
"font: 75 12pt \"Rockwell\";")
        self.Enter.setObjectName("Enter")
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setGeometry(QtCore.QRect(290, 500, 311, 21))
        self.errorLabel.setStyleSheet("color:rgb(255, 0, 0); background:rgb(0, 0, 0)")
        self.errorLabel.setObjectName("errorLabel")
        self.Password = QtWidgets.QLineEdit(self.widget)
        self.Password.setGeometry(QtCore.QRect(760, 600, 481, 41))
        self.Password.setStyleSheet("background:rgb(255, 255, 255);\n"
"font: 10pt \"Candara\";")
        self.Password.setObjectName("Password")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(870, 550, 261, 41))
        self.label_5.setStyleSheet("color:rgb(85, 255, 255);\n"
"font:;\n"
"font: 12pt \"Bahnschrift SemiLight\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(870, 430, 261, 51))
        self.label_6.setStyleSheet("color:rgb(85, 255, 255);\n"
"font:;\n"
"font: 12pt \"Bahnschrift SemiLight\";")
        self.label_6.setObjectName("label_6")
        self.Back = QtWidgets.QPushButton(self.widget)
        self.Back.setGeometry(QtCore.QRect(30, 20, 91, 41))
        self.Back.setStyleSheet("background-color:rgb(255, 0,0);\n"
"font: 63 10pt \"Bahnschrift SemiBold\";")
        self.Back.setObjectName("Back")
        self.successLabel = QtWidgets.QLabel(self.widget)
        self.successLabel.setGeometry(QtCore.QRect(950, 800, 111, 31))
        self.successLabel.setMouseTracking(True)
        self.successLabel.setAutoFillBackground(False)
        self.successLabel.setStyleSheet("color:rgb(85, 255, 0);")
        self.successLabel.setObjectName("successLabel")
        self.errorLabelPassword = QtWidgets.QLabel(self.widget)
        self.errorLabelPassword.setGeometry(QtCore.QRect(760, 660, 401, 16))
        self.errorLabelPassword.setStyleSheet("color:red;\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.errorLabelPassword.setText("")
        self.errorLabelPassword.setObjectName("errorLabelPassword")
        self.errorLabelUsername = QtWidgets.QLabel(self.widget)
        self.errorLabelUsername.setGeometry(QtCore.QRect(760, 540, 401, 16))
        self.errorLabelUsername.setStyleSheet("color:red;")
        self.errorLabelUsername.setText("")
        self.errorLabelUsername.setObjectName("errorLabelUsername")
        self.ForgotPassword = QtWidgets.QPushButton(self.widget)
        self.ForgotPassword.setGeometry(QtCore.QRect(1310, 610, 111, 28))
        self.ForgotPassword.setStyleSheet("background-color:rgb(255, 170, 0)")
        self.ForgotPassword.setObjectName("ForgotPassword")
        self.LabelPasswordHint = QtWidgets.QLabel(self.widget)
        self.LabelPasswordHint.setGeometry(QtCore.QRect(1310, 650, 551, 31))
        self.LabelPasswordHint.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"color:rgb(170, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.LabelPasswordHint.setText("")
        self.LabelPasswordHint.setObjectName("LabelPasswordHint")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Before you start, let\'s check wheather you are the real user<br/>or not!</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Wait!!!</p></body></html>"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.Enter.setText(_translate("Dialog", "Enter"))
        self.errorLabel.setText(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Enter your password:</p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Enter your username:</p></body></html>"))
        self.Back.setText(_translate("Dialog", "Back"))
        self.successLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.ForgotPassword.setText(_translate("Dialog", "Forgot Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
